// --- ESTADO ---
let investments = [];
let transactions = [];
let plans = [];

let config = {
    giroCategories: ['Investimento', 'Transferência', 'Resgate'],
    giroAccounts: ['Carteira Pessoal', 'Conta Bancária', 'Corretora'],
    personalCategories: ['Alimentação', 'Transporte', 'Saúde', 'Lazer'],
    personalSubcategories: ['Restaurante', 'Supermercado', 'Uber', 'Ônibus', 'Farmácia'],
    personalAccounts: ['Dinheiro', 'Conta Bancária', 'Carteira de Giro']
};

let evolutionPage = 1;
const ITEMS_PER_PAGE = 15;
let filteredEvolutionData = [];

// URL DO APP SCRIPT
const GOOGLE_SHEET_URL = "https://script.google.com/macros/s/AKfycbyAG1s5Z51pTrXSn4HY0rF_yBUPGBJ0NNpyUsfZaUKh3Zp9Sm7Su5QNlYXWxwCTE9s/exec";

// INSTÂNCIAS GRÁFICOS
let charts = { pie: null, bar: null, evo: null, exp: null, comp: null };

window.onload = function() {
    loadLocal();
    initDates();
    renderAll();
    loadFromSheet();
    setTimeout(() => { populateAllSelects(); }, 50);
    
    // Handlers de formulários
    const investForm = document.getElementById('investForm');
    if(investForm) investForm.onsubmit = (e) => {
        e.preventDefault();
        const b = calculateBalances();
        const val = parseFloat(getVal('inpValue'));
        if(val > b.reinvest) return alert("Saldo insuficiente no Giro!");
        
        const realized = document.querySelector('input[name="inpRealized"]:checked').value === 'yes';
        
        const newI = {
            dataType: 'investment', id: Date.now(),
            name: getVal('inpName'), institution: getVal('inpInst'),
            type: getVal('inpType'), value: val, date: getVal('inpDate'),
            expiry: getVal('inpExpiry'), ratePrev: getVal('inpRatePrev'),
            rateTypePrev: getVal('inpRateTypePrev'), status: getVal('inpStatus'),
            realized: realized
        };
        const sync = {
            dataType: 'transaction', id: Date.now()+1,
            date: newI.date, type: 'withdraw', wallet: 'reinvest',
            desc: `Aporte: ${newI.name}`, value: val,
            realized: realized
        };
        investments.push(newI); transactions.unshift(sync);
        saveLocal(); renderAll(); sendToSheet(newI); sendToSheet(sync);
        e.target.reset(); alert("Aporte salvo!");
    };

    const planForm = document.getElementById('planForm');
    if(planForm) planForm.onsubmit = (e) => {
        e.preventDefault();
        const realized = document.querySelector('input[name="planRealized"]:checked').value === 'yes';
        const newP = { 
            id: Date.now(), 
            monthYear: getVal('inpPlanMonth'), 
            targetValue: parseFloat(getVal('inpPlanValue')), 
            category: getVal('inpPlanCategory'),
            realized: realized
        };
        plans.push(newP); saveLocal(); renderPlansTable(); alert("Meta salva!");
    };

    const personalTxForm = document.getElementById('personalTransactionForm');
    if(personalTxForm) personalTxForm.onsubmit = (e) => {
        e.preventDefault();
        
        const name = getVal('ptxName');
        const category = getVal('ptxCategory');
        const subcategory = getVal('ptxSubcategory');
        const date = getVal('ptxDate');
        const value = parseFloat(getVal('ptxValue'));
        const type = getVal('ptxType');
        const realized = document.querySelector('input[name="ptxRealized"]:checked').value === 'yes';
        const account = getVal('ptxAccount');
        
        if(!name || !category || !date || !value || !type) {
            return alert("Preencha todos os campos obrigatórios!");
        }
        
        const newT = {
            dataType: 'transaction', 
            id: Date.now(),
            date: date,
            type: type,
            wallet: 'personal',
            desc: `${category} - ${subcategory ? subcategory + ' - ' : ''}${name}`,
            value: value,
            category: category,
            subcategory: subcategory,
            account: account,
            realized: realized
        };
        
        transactions.unshift(newT);
        saveLocal(); 
        renderAll(); 
        sendToSheet(newT);
        
        if(type === 'withdraw' && account && (config.giroAccounts || []).includes(account)) {
            const autoT = {
                dataType: 'transaction',
                id: Date.now() + 0.5,
                date: date,
                type: 'deposit',
                wallet: 'reinvest',
                desc: `Auto: ${name}`,
                value: value,
                category: 'Entrada Pessoal',
                account: account,
                realized: realized,
                autoGenerated: true
            };
            transactions.unshift(autoT);
            sendToSheet(autoT);
        }
        
        e.target.reset();
        alert("Transação registrada!");
    };

    const giroTxForm = document.getElementById('giroTransactionForm');
    if(giroTxForm) giroTxForm.onsubmit = (e) => {
        e.preventDefault();
        
        const name = getVal('gtxName');
        const category = getVal('gtxCategory');
        const account = getVal('gtxAccount');
        const date = getVal('gtxDate');
        const value = parseFloat(getVal('gtxValue'));
        const type = getVal('gtxType');
        const realized = document.querySelector('input[name="gtxRealized"]:checked').value === 'yes';
        
        if(!name || !category || !date || !value || !type) {
            return alert("Preencha todos os campos obrigatórios!");
        }
        
        const newT = {
            dataType: 'transaction', 
            id: Date.now(),
            date: date,
            type: type,
            wallet: 'reinvest',
            desc: `${category} - ${account ? account + ' - ' : ''}${name}`,
            value: value,
            category: category,
            account: account,
            realized: realized
        };
        
        transactions.unshift(newT);
        saveLocal(); 
        renderAll(); 
        sendToSheet(newT);
        
        if(type === 'withdraw' && account === 'Carteira Pessoal') {
            const autoT = {
                dataType: 'transaction',
                id: Date.now() + 0.5,
                date: date,
                type: 'deposit',
                wallet: 'personal',
                desc: `Auto: ${name}`,
                value: value,
                category: 'Entrada Giro',
                realized: realized,
                autoGenerated: true
            };
            transactions.unshift(autoT);
            sendToSheet(autoT);
        }
        
        e.target.reset();
        alert("Movimentação registrada!");
    };
};

// --- NAVEGAÇÃO ---
function showPage(id, el) {
    document.querySelectorAll('.page-section').forEach(s => s.classList.remove('active-section'));
    if(el) {
        document.querySelectorAll('.menu-item').forEach(i => i.classList.remove('active'));
        el.classList.add('active');
    }
    const target = document.getElementById(id);
    if(target) {
        target.classList.add('active-section');
        updateCurrentPage(id);
    }
}

function updateCurrentPage(id) {
    if(id === 'dashboard') updateDashboard();
    if(id === 'despesas') renderExpenseAnalysis();
    if(id === 'evolucao') updateEvolutionChart();
    if(id === 'comparativo') updateComparisonDashboard();
}

function checkPasswordAndShowConfig(el) {
    const p = prompt("Senha de acesso:");
    if(p === '2915') showPage('config', el);
}

function updateGiroAccountVisibility() {
    const tipo = getVal('gtxType');
    const accountGroup = document.getElementById('giroAccountGroup');
    if(accountGroup) {
        accountGroup.style.display = tipo === 'withdraw' ? 'block' : 'none';
    }
}

// --- DATAS ---
function initDates() {
    const now = new Date();
    const firstDay = new Date(now.getFullYear(), now.getMonth(), 1);
    
    setVal('dashGlobalStart', firstDay.toISOString().split('T')[0]);
    setVal('dashGlobalEnd', now.toISOString().split('T')[0]);

    const lastYear = new Date();
    lastYear.setFullYear(now.getFullYear() - 1);
    setVal('filterStartDate', lastYear.toISOString().split('T')[0]);
    setVal('filterEndDate', now.toISOString().split('T')[0]);
}

// --- SALDOS ---
function calculateBalances() {
    let re = 0, pe = 0;
    transactions.forEach(t => {
        const v = parseFloat(t.value) || 0;
        if(t.wallet === 'reinvest') t.type === 'deposit' ? re += v : re -= v;
        else if(t.wallet === 'personal') t.type === 'deposit' ? pe += v : pe -= v;
    });
    return { reinvest: re, personal: pe };
}

// --- CONFIGURAÇÕES ---
function addConfig(key, inputId) {
    const raw = getVal(inputId);
    const val = raw ? raw.trim() : '';
    if(!val) return alert("Digite um valor!");
    if(!config[key]) config[key] = [];
    if(config[key].includes(val)) { setVal(inputId, ''); return alert('Já existe este item.'); }
    config[key].push(val);
    config[key] = Array.from(new Set(config[key].map(i => i.trim()).filter(Boolean))).sort();
    saveLocal();
    renderConfigTables();
    populateAllSelects();
    setVal(inputId, '');
}

function removeConfig(key, index) {
    config[key].splice(index, 1);
    saveLocal();
    renderConfigTables();
    populateAllSelects();
}

function renderConfigTables() {
    renderConfigTable('giroCategories', 'configGiroCategoryTable');
    renderConfigTable('giroAccounts', 'configGiroAccountTable');
    renderConfigTable('personalCategories', 'configPersonalCategoryTable');
    renderConfigTable('personalSubcategories', 'configPersonalSubcategoryTable');
    renderConfigTable('personalAccounts', 'configPersonalAccountTable');
    populateAllSelects();
}

function renderConfigTable(key, tableId) {
    const tb = document.getElementById(tableId);
    if(!tb) return;
    tb.innerHTML = '';
    const items = config[key] || [];
    items.forEach((item, idx) => {
        tb.innerHTML += `<tr style="border-bottom: 1px solid var(--border-color); padding: 8px 0;">
            <td style="padding: 8px;">${item}</td>
            <td style="text-align: right; padding: 8px;"><button class="btn btn-danger" onclick="removeConfig('${key}', ${idx})" style="padding: 4px 8px; font-size: 12px;">🗑️</button></td>
        </tr>`;
    });
}

function populateSelect(selectId, items) {
    const select = document.getElementById(selectId);
    if(!select) return;
    const currentValue = select.value;
    const list = (items || []).map(i => (i || '').toString().trim()).filter(Boolean);
    const uniq = Array.from(new Set(list));
    select.innerHTML = '<option value="">Selecione...</option>';
    uniq.forEach(item => {
        const option = document.createElement('option');
        option.value = item;
        option.text = item;
        select.appendChild(option);
    });
    if(currentValue) select.value = currentValue;
}

function populateAllSelects() {
    populateSelect('gtxCategory', config.giroCategories || []);
    populateSelect('gtxAccount', config.giroAccounts || []);
    populateSelect('ptxCategory', config.personalCategories || []);
    populateSelect('ptxSubcategory', config.personalSubcategories || []);
    populateSelect('ptxAccount', config.personalAccounts || []);
}

// --- RENDERIZAÇÃO ---
function renderAll() {
    const saldos = calculateBalances();
    setTxt('balanceReinvest', formatCurrency(saldos.reinvest));
    setTxt('balancePersonal', formatCurrency(saldos.personal));
    
    renderReinvestTransactionTables();
    renderPersonalTransactionTables();
    updateDashboard();
    renderPlansTable();
    renderHistory();
    
    const despesasSection = document.getElementById('despesas');
    if(despesasSection && despesasSection.classList.contains('active-section')) {
        renderExpenseAnalysis();
        populateAllSelects();
    }
}

function renderTable(id, wallet) {
    const tb = document.getElementById(id); if(!tb) return;
    tb.innerHTML = '';
    transactions.filter(t => t.wallet === wallet).forEach(t => {
        tb.innerHTML += `<tr>
            <td>${t.date.split('-').reverse().join('/')}</td>
            <td class="${t.type==='deposit'?'text-green':'text-red'}">${t.type==='deposit'?'Entrada':'Saída'}</td>
            <td>${t.desc}</td>
            <td>${formatCurrency(t.value)}</td>
            <td><button onclick="deleteTransaction(${t.id})" style="padding: 4px 8px; font-size: 12px;" class="btn btn-danger">🗑️</button></td>
        </tr>`;
    });
}

function renderReinvestTransactionTables() {
    const pendingTb = document.getElementById('tableBodyReinvestPending');
    const realizedTb = document.getElementById('tableBodyReinvestRealized');
    
    if(!pendingTb || !realizedTb) return;
    
    pendingTb.innerHTML = '';
    realizedTb.innerHTML = '';
    
    const giroTx = transactions.filter(t => t.wallet === 'reinvest');
    
    giroTx.forEach(t => {
        const isRealized = t.realized === true || t.realized === 'yes';
        const row = `<tr>
            <td>${t.date.split('-').reverse().join('/')}</td>
            <td class="${t.type==='deposit'?'text-green':'text-red'}">${t.type==='deposit'?'Entrada':'Saída'}</td>
            <td>${t.desc}</td>
            <td>${formatCurrency(t.value)}</td>
            <td style="display: flex; gap: 5px;">
                <button onclick="editTransaction(${t.id})" style="padding: 4px 8px; font-size: 12px;" class="btn btn-blue">✏️</button>
                <button onclick="deleteTransaction(${t.id})" style="padding: 4px 8px; font-size: 12px;" class="btn btn-danger">🗑️</button>
            </td>
        </tr>`;
        
        if(isRealized) {
            realizedTb.innerHTML += row;
        } else {
            pendingTb.innerHTML += row;
        }
    });
}

function renderPersonalTransactionTables() {
    const pendingTb = document.getElementById('tableBodyPersonalPending');
    const realizedTb = document.getElementById('tableBodyPersonalRealized');
    
    if(!pendingTb || !realizedTb) return;
    
    pendingTb.innerHTML = '';
    realizedTb.innerHTML = '';
    
    const personalTx = transactions.filter(t => t.wallet === 'personal');
    
    personalTx.forEach(t => {
        const isRealized = t.realized === true || t.realized === 'yes';
        const row = `<tr>
            <td>${t.date.split('-').reverse().join('/')}</td>
            <td class="${t.type==='deposit'?'text-green':'text-red'}">${t.type==='deposit'?'Entrada':'Saída'}</td>
            <td>${t.desc}</td>
            <td>${formatCurrency(t.value)}</td>
            <td style="display: flex; gap: 5px;">
                <button onclick="editTransaction(${t.id})" style="padding: 4px 8px; font-size: 12px;" class="btn btn-blue">✏️</button>
                <button onclick="deleteTransaction(${t.id})" style="padding: 4px 8px; font-size: 12px;" class="btn btn-danger">🗑️</button>
            </td>
        </tr>`;
        
        if(isRealized) {
            realizedTb.innerHTML += row;
        } else {
            pendingTb.innerHTML += row;
        }
    });
}

// --- DASHBOARD ---
function updateDashboard() {
    const startStr = getVal('dashGlobalStart') || new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split('T')[0];
    const endStr = getVal('dashGlobalEnd') || new Date().toISOString().split('T')[0];
    const start = new Date(startStr);
    const end = new Date(endStr);
    const b = calculateBalances();

    let incRealized = 0, expRealized = 0, incPrev = 0, expPrev = 0;
    transactions.forEach(t => {
        const d = new Date(t.date);
        if(d >= start && d <= end) {
            const isRealized = t.realized === true || t.realized === 'yes';
            if(isRealized) {
                t.type === 'deposit' ? incRealized += t.value : expRealized += t.value;
            } else {
                t.type === 'deposit' ? incPrev += t.value : expPrev += t.value;
            }
        }
    });

    setTxt('dashPeriodIncomePrev', formatCurrency(incPrev));
    setTxt('dashPeriodIncome', formatCurrency(incRealized));
    setTxt('dashPeriodExpensePrev', formatCurrency(expPrev));
    setTxt('dashPeriodExpense', formatCurrency(expRealized));
    
    const investedRealized = investments.filter(i => i.realized === true || i.realized === 'yes').reduce((a, b) => a + (parseFloat(b.value)||0), 0);
    const investedPrev = investments.filter(i => i.realized !== true && i.realized !== 'yes').reduce((a, b) => a + (parseFloat(b.value)||0), 0);
    setTxt('dashTotalInvestedPrev', formatCurrency(investedPrev));
    setTxt('dashTotalInvested', formatCurrency(investedRealized));
    
    const bPrev = calculateBalancesRealized(false);
    const bReal = calculateBalancesRealized(true);
    setTxt('dashBalanceReinvestPrev', formatCurrency(bPrev.reinvest));
    setTxt('dashBalanceReinvest', formatCurrency(bReal.reinvest));

    renderDashCharts(incRealized, expRealized);
}

function calculateBalancesRealized(realized = true) {
    let re = 0, pe = 0;
    const filter = realized ? (t => t.realized === true || t.realized === 'yes') : (t => t.realized !== true && t.realized !== 'yes');
    transactions.filter(filter).forEach(t => {
        const v = parseFloat(t.value) || 0;
        if(t.wallet === 'reinvest') t.type === 'deposit' ? re += v : re -= v;
        else if(t.wallet === 'personal') t.type === 'deposit' ? pe += v : pe -= v;
    });
    return { reinvest: re, personal: pe };
}

function renderDashCharts(incReal, expReal) {
    let incPrev = 0, expPrev = 0;
    transactions.forEach(t => {
        if(t.realized !== true && t.realized !== 'yes') {
            t.type === 'deposit' ? incPrev += t.value : expPrev += t.value;
        }
    });
    
    const ctx = document.getElementById('barChartDash'); if(!ctx) return;
    if(charts.bar) charts.bar.destroy();
    charts.bar = new Chart(ctx, {
        type: 'bar',
        data: { 
            labels: ['Receitas', 'Despesas'], 
            datasets: [
                { label: 'Previsto', data: [incPrev, expPrev], backgroundColor: 'rgba(0,184,148,0.3)' },
                { label: 'Realizado', data: [incReal, expReal], backgroundColor: ['#00b894', '#ff7675'] }
            ] 
        },
        options: { responsive: true, maintainAspectRatio: false, scales: { y: { stacked: false } } }
    });
    renderPieChart();
}

function renderPieChart() {
    const ctx = document.getElementById('pieChart'); if(!ctx) return;
    const types = {};
    investments.forEach(i => types[i.type] = (types[i.type] || 0) + (parseFloat(i.value)||0));
    if(charts.pie) charts.pie.destroy();
    charts.pie = new Chart(ctx.getContext('2d'), {
        type: 'doughnut',
        data: { labels: Object.keys(types), datasets: [{ data: Object.values(types), backgroundColor: ['#0984e3', '#00b894', '#6c5ce7', '#ff7675', '#fdcb6e'] }] },
        options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'right', labels: { color: '#fff' } } } }
    });
}

// --- DESPESAS ---
function renderExpenseAnalysis() {
    const container = document.getElementById('expenseTree');
    const tableBody = document.getElementById('expenseTableBody');
    if(!container || !tableBody) return;
    
    container.innerHTML = ''; tableBody.innerHTML = '';
    const expenses = transactions.filter(t => t.type === 'withdraw' && t.wallet === 'personal');
    const categories = {};
    
    expenses.forEach(e => {
        const cat = e.desc.split(' ')[0] || 'Geral';
        if(!categories[cat]) categories[cat] = { total: 0, items: [] };
        categories[cat].total += parseFloat(e.value) || 0;
        categories[cat].items.push(e);
        tableBody.innerHTML += `<tr><td>${e.date}</td><td>${cat}</td><td>${e.desc}</td><td>${formatCurrency(e.value)}</td></tr>`;
    });

    for(let cat in categories) {
        const node = document.createElement('div');
        node.className = 'tree-node';
        node.innerHTML = `<div class="tree-category"><span>${cat}</span><span>${formatCurrency(categories[cat].total)}</span></div>`;
        categories[cat].items.forEach(item => {
            node.innerHTML += `<div class="tree-item"><span>${item.desc}</span><span>${formatCurrency(item.value)}</span></div>`;
        });
        container.appendChild(node);
    }

    const canvasContainer = document.getElementById('expenseCompareChart');
    if(canvasContainer) {
        try {
            const catNames = Object.keys(categories);
            const catValues = catNames.map(cat => categories[cat].total);
            const colors = ['#ff7675', '#fd79a8', '#fdcb6e', '#6c5ce7', '#0984e3', '#00b894', '#e17055', '#74b9ff', '#a29bfe', '#fab1a0'];
            
            if(charts.exp) {
                charts.exp.destroy();
                charts.exp = null;
            }
            
            if(catNames.length > 0) {
                charts.exp = new Chart(canvasContainer, {
                    type: 'doughnut',
                    data: { 
                        labels: catNames, 
                        datasets: [{ 
                            data: catValues, 
                            backgroundColor: colors.slice(0, catNames.length)
                        }] 
                    },
                    options: { 
                        responsive: true, 
                        maintainAspectRatio: false,
                        plugins: {
                            legend: { position: 'bottom' }
                        }
                    }
                });
            }
        } catch(err) {
            console.error('Erro ao renderizar gráfico de despesas:', err);
        }
    }
}

// --- EVOLUÇÃO ---
function updateEvolutionChart() {
    const ctx = document.getElementById('evolutionChart'); if(!ctx) return;
    const startStr = getVal('filterStartDate');
    const endStr = getVal('filterEndDate');
    const typeF = getVal('filterType');

    const startDate = new Date(startStr);
    const endDate = new Date(endStr);
    const filteredInv = investments.filter(i => typeF === 'all' || i.type === typeF);

    const labels = [];
    const dataPoints = [];
    const tableData = [];

    let curr = new Date(startDate.getFullYear(), startDate.getMonth(), 1);
    const limit = new Date(endDate.getFullYear(), endDate.getMonth() + 1, 0);
    let prevVal = 0;

    while (curr <= limit) {
        const label = `${String(curr.getMonth()+1).padStart(2,'0')}/${curr.getFullYear()}`;
        let total = 0;
        
        filteredInv.forEach(inv => {
            const p = inv.date.split('-');
            const iDate = new Date(p[0], p[1]-1, p[2]);

            if (curr >= iDate) {
                const diffM = (curr - iDate) / (1000 * 60 * 60 * 24 * 30.44);
                let taxaA = 0.10; 
                if (inv.ratePrev) {
                   const r = parseFloat(inv.ratePrev);
                   if (inv.rateTypePrev.includes('CDI')) taxaA = (r/100) * 0.1125;
                   else if (inv.rateTypePrev.includes('IPCA')) taxaA = 0.045 + (r/100);
                   else taxaA = r/100;
                }
                const taxaM = Math.pow(1 + taxaA, 1/12) - 1;
                total += inv.value * Math.pow(1 + taxaM, Math.max(0, diffM));
            }
        });

        labels.push(label);
        dataPoints.push(total);
        tableData.push({ date: label, total, growth: dataPoints.length === 1 ? 0 : total - prevVal });
        prevVal = total;
        curr.setMonth(curr.getMonth() + 1);
    }

    if(charts.evo) charts.evo.destroy();
    charts.evo = new Chart(ctx.getContext('2d'), {
        type: 'line',
        data: { labels, datasets: [{ label: 'Patrimônio Projetado', data: dataPoints, borderColor: '#00b894', fill: true, backgroundColor: 'rgba(0,184,148,0.1)', tension: 0.3 }] },
        options: { responsive: true, maintainAspectRatio: false }
    });

    filteredEvolutionData = tableData;
    evolutionPage = 1;
    renderEvoTable();
}

function renderEvoTable() {
    const tb = document.querySelector('#evolutionTable tbody'); if(!tb) return;
    tb.innerHTML = '';
    const start = (evolutionPage - 1) * ITEMS_PER_PAGE;
    filteredEvolutionData.slice(start, start + ITEMS_PER_PAGE).forEach(r => {
        tb.innerHTML += `<tr><td>${r.date}</td><td>${formatCurrency(r.total)}</td><td class="${r.growth>=0?'text-green':'text-red'}">${formatCurrency(r.growth)}</td></tr>`;
    });
    setTxt('pageIndicator', `Página ${evolutionPage}`);
}

function changeEvoPage(dir) {
    const max = Math.ceil(filteredEvolutionData.length / ITEMS_PER_PAGE);
    if(dir === 1 && evolutionPage < max) { evolutionPage++; renderEvoTable(); }
    else if(dir === -1 && evolutionPage > 1) { evolutionPage--; renderEvoTable(); }
}

// --- COMPARATIVO ---
function updateComparisonDashboard() {
    const realized = {};
    investments.forEach(inv => {
        const key = inv.date.slice(0, 7);
        realized[key] = (realized[key] || 0) + parseFloat(inv.value);
    });
    const planned = {};
    plans.forEach(p => {
        const key = p.monthYear;
        planned[key] = (planned[key] || 0) + parseFloat(p.targetValue);
    });

    const months = Array.from(new Set([...Object.keys(realized), ...Object.keys(planned)])).sort();
    const tP = Object.values(planned).reduce((a,b)=>a+b, 0);
    const tR = Object.values(realized).reduce((a,b)=>a+b, 0);
    
    setTxt('compTotalPlanned', formatCurrency(tP));
    setTxt('compTotalRealized', formatCurrency(tR));
    setTxt('compPercentage', tP > 0 ? ((tR/tP)*100).toFixed(1) + '%' : '0%');

    const ctx = document.getElementById('compBarChart'); if(!ctx) return;
    if(charts.comp) charts.comp.destroy();
    charts.comp = new Chart(ctx.getContext('2d'), {
        type: 'bar',
        data: { labels: months, datasets: [
            { label: 'Planejado', data: months.map(m => planned[m] || 0), backgroundColor: 'rgba(255,255,255,0.1)' },
            { label: 'Realizado', data: months.map(m => realized[m] || 0), backgroundColor: '#00b894' }
        ]},
        options: { responsive: true, maintainAspectRatio: false }
    });
}

// --- FORMS ---
document.getElementById('investForm').onsubmit = (e) => {
    e.preventDefault();
    const b = calculateBalances();
    const val = parseFloat(getVal('inpValue'));
    if(val > b.reinvest) return alert("Saldo insuficiente no Giro!");
    
    const realized = document.querySelector('input[name="inpRealized"]:checked').value === 'yes';
    
    const newI = {
        dataType: 'investment', id: Date.now(),
        name: getVal('inpName'), institution: getVal('inpInst'),
        type: getVal('inpType'), value: val, date: getVal('inpDate'),
        expiry: getVal('inpExpiry'), ratePrev: getVal('inpRatePrev'),
        rateTypePrev: getVal('inpRateTypePrev'), status: getVal('inpStatus'),
        realized: realized
    };
    const sync = {
        dataType: 'transaction', id: Date.now()+1,
        date: newI.date, type: 'withdraw', wallet: 'reinvest',
        desc: `Aporte: ${newI.name}`, value: val,
        realized: realized
    };
    investments.push(newI); transactions.unshift(sync);
    saveLocal(); renderAll(); sendToSheet(newI); sendToSheet(sync);
    e.target.reset(); alert("Aporte salvo!");
};

document.getElementById('planForm').onsubmit = (e) => {
    e.preventDefault();
    const realized = document.querySelector('input[name="planRealized"]:checked').value === 'yes';
    const newP = { 
        id: Date.now(), 
        monthYear: getVal('inpPlanMonth'), 
        targetValue: parseFloat(getVal('inpPlanValue')), 
        category: getVal('inpPlanCategory'),
        realized: realized
    };
    plans.push(newP); saveLocal(); renderPlansTable(); alert("Meta salva!");
};

document.getElementById('personalTransactionForm').onsubmit = (e) => {
    e.preventDefault();
    
    const name = getVal('ptxName');
    const category = getVal('ptxCategory');
    const subcategory = getVal('ptxSubcategory');
    const date = getVal('ptxDate');
    const value = parseFloat(getVal('ptxValue'));
    const type = getVal('ptxType');
    const realized = document.querySelector('input[name="ptxRealized"]:checked').value === 'yes';
    const account = getVal('ptxAccount');
    
    if(!name || !category || !date || !value || !type) {
        return alert("Preencha todos os campos obrigatórios!");
    }
    
    const newT = {
        dataType: 'transaction', 
        id: Date.now(),
        date: date,
        type: type,
        wallet: 'personal',
        desc: `${category} - ${subcategory ? subcategory + ' - ' : ''}${name}`,
        value: value,
        category: category,
        subcategory: subcategory,
        account: account,
        realized: realized
    };
    
    transactions.unshift(newT);
    saveLocal(); 
    renderAll(); 
    sendToSheet(newT);
    
    if(type === 'withdraw' && account && (config.giroAccounts || []).includes(account)) {
        const autoT = {
            dataType: 'transaction',
            id: Date.now() + 0.5,
            date: date,
            type: 'deposit',
            wallet: 'reinvest',
            desc: `Auto: ${name}`,
            value: value,
            category: 'Entrada Pessoal',
            account: account,
            realized: realized,
            autoGenerated: true
        };
        transactions.unshift(autoT);
        sendToSheet(autoT);
    }
    
    e.target.reset();
    alert("Transação registrada!");
};

document.getElementById('giroTransactionForm').onsubmit = (e) => {
    e.preventDefault();
    
    const name = getVal('gtxName');
    const category = getVal('gtxCategory');
    const account = getVal('gtxAccount');
    const date = getVal('gtxDate');
    const value = parseFloat(getVal('gtxValue'));
    const type = getVal('gtxType');
    const realized = document.querySelector('input[name="gtxRealized"]:checked').value === 'yes';
    
    if(!name || !category || !date || !value || !type) {
        return alert("Preencha todos os campos obrigatórios!");
    }
    
    const newT = {
        dataType: 'transaction', 
        id: Date.now(),
        date: date,
        type: type,
        wallet: 'reinvest',
        desc: `${category} - ${account ? account + ' - ' : ''}${name}`,
        value: value,
        category: category,
        account: account,
        realized: realized
    };
    
    transactions.unshift(newT);
    saveLocal(); 
    renderAll(); 
    sendToSheet(newT);
    
    if(type === 'withdraw' && account === 'Carteira Pessoal') {
        const autoT = {
            dataType: 'transaction',
            id: Date.now() + 0.5,
            date: date,
            type: 'deposit',
            wallet: 'personal',
            desc: `Auto: ${name}`,
            value: value,
            category: 'Entrada Giro',
            realized: realized,
            autoGenerated: true
        };
        transactions.unshift(autoT);
        sendToSheet(autoT);
    }
    
    e.target.reset();
    alert("Movimentação registrada!");
};

// --- PERSISTÊNCIA & SHEET ---
function formatCurrency(v) { return (v || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function getVal(id) { const el = document.getElementById(id); return el ? el.value : ''; }
function setVal(id, v) { const el = document.getElementById(id); if(el) el.value = v; }
function setTxt(id, t) { const el = document.getElementById(id); if(el) el.innerText = t; }

function saveLocal() {
    localStorage.setItem('investments', JSON.stringify(investments));
    localStorage.setItem('transactions', JSON.stringify(transactions));
    localStorage.setItem('plans', JSON.stringify(plans));
    localStorage.setItem('config', JSON.stringify(config));
}

function loadLocal() {
    investments = JSON.parse(localStorage.getItem('investments')) || [];
    transactions = JSON.parse(localStorage.getItem('transactions')) || [];
    plans = JSON.parse(localStorage.getItem('plans')) || [];
    const savedConfig = JSON.parse(localStorage.getItem('config')) || {};
    config = Object.assign({}, config, savedConfig);
    renderConfigTables();
}

async function sendToSheet(d) {
    try {
        const res = await fetch(GOOGLE_SHEET_URL, { method: 'POST', mode: 'no-cors', body: JSON.stringify(d) });
        if (res) {
            console.log('sendToSheet: response type=', res.type, 'status=', res.status);
        }
    } catch (e) {
        console.error('sendToSheet error:', e);
    }
}

async function loadFromSheet() {
    const ind = document.getElementById('syncIndicator');
    try {
        const old = document.getElementById('jsonpSheetScript');
        if (old) old.remove();

        if (window._sheetJsonpTimeout) clearTimeout(window._sheetJsonpTimeout);

        window.handleSheetData = function(d) {
            try {
                if (window._sheetJsonpTimeout) { clearTimeout(window._sheetJsonpTimeout); window._sheetJsonpTimeout = null; }
                if (d && d.investments) {
                    investments = d.investments || [];
                }
                if (d && d.transactions) {
                    transactions = d.transactions || [];
                }
                if(ind) { ind.innerText = 'Online'; ind.className = 'status-indicator status-online'; }
                renderAll();
                populateAllSelects();
            } catch(err) {
                console.error('handleSheetData error:', err);
                if(ind) { ind.innerText = 'Local'; ind.className = 'status-indicator status-offline'; }
            }
        };

        const url = `${GOOGLE_SHEET_URL}?t=${Date.now()}&callback=handleSheetData`;
        const s = document.createElement('script');
        s.id = 'jsonpSheetScript';
        s.src = url;
        s.async = true;
        s.onerror = function() {
            console.error('JSONP script error loading', url);
            if(ind) { ind.innerText = 'Local'; ind.className = 'status-indicator status-offline'; }
        };
        document.head.appendChild(s);

        window._sheetJsonpTimeout = setTimeout(function() {
            console.error('JSONP timeout waiting for sheet data');
            if(ind) { ind.innerText = 'Local'; ind.className = 'status-indicator status-offline'; }
        }, 8000);

    } catch(e) {
        console.error('loadFromSheet error:', e);
        if(ind) { ind.innerText = 'Local'; ind.className = 'status-indicator status-offline'; }
    }
}

// Função para TESTAR a URL do Apps Script (chame esto no console)
window.testGoogleSheetsConnection = function() {
    console.log('%c=== TESTE DE CONEXÃO GOOGLE SHEETS ===', 'color: blue; font-size: 14px; font-weight: bold;');
    console.log('URL do Apps Script:', GOOGLE_SHEET_URL);
    
    const testUrl = `${GOOGLE_SHEET_URL}?t=${Date.now()}`;
    console.log('URL de teste (GET):', testUrl);
    
    // Teste 1: JSONP
    console.log('%cTeste 1: JSONP', 'color: green; font-weight: bold;');
    window._testJsonpCallback = function(data) {
        console.log('%c✓ JSONP funcionando!', 'color: green; font-weight: bold;');
        console.log('Dados recebidos:', data);
        delete window._testJsonpCallback;
    };
    
    const s = document.createElement('script');
    s.src = `${GOOGLE_SHEET_URL}?t=${Date.now()}&callback=_testJsonpCallback`;
    s.onerror = function() {
        console.error('%c✗ Erro ao carregar JSONP', 'color: red; font-weight: bold;');
    };
    
    const timeout = setTimeout(() => {
        console.error('%c✗ JSONP timeout (8 segundos) - Apps Script pode estar inacessível', 'color: orange; font-weight: bold;');
    }, 8000);
    
    s.onload = function() {
        clearTimeout(timeout);
    };
    
    document.head.appendChild(s);
    
    // Teste 2: Verificar localStorage
    console.log('%cTeste 2: Dados em localStorage', 'color: green; font-weight: bold;');
    const local = {
        investments: investments.length,
        transactions: transactions.length,
        plans: plans.length,
        config: Object.keys(config).length
    };
    console.log('Dados salvos localmente:', local);
};
function deleteTransaction(id) { if(confirm("Apagar?")) { transactions = transactions.filter(t=>t.id!==id); saveLocal(); renderAll(); } }
function editTransaction(id) { 
    const tx = transactions.find(t => t.id === id);
    if(!tx) return alert("Transação não encontrada");
    
    const newRealized = confirm("Marcar como realizado?");
    tx.realized = newRealized ? 'yes' : 'no';
    saveLocal(); 
    renderAll();
}
function deleteInvestment(id) { if(confirm("Apagar?")) { investments = investments.filter(i=>i.id!==id); saveLocal(); renderAll(); } }
function clearAllData() { if(confirm("Limpar local?")) { localStorage.clear(); location.reload(); } }

function renderPlansTable() {
    const tb = document.getElementById('plansTableBody'); if(!tb) return;
    tb.innerHTML = '';
    plans.forEach(p => {
        const isRealized = p.realized === true || p.realized === 'yes';
        tb.innerHTML += `<tr><td>${p.monthYear}</td><td>${p.category}</td><td>${formatCurrency(p.targetValue)}</td><td><span class="${isRealized ? 'text-green' : 'text-red'}">${isRealized ? '✓ Sim' : '✗ Não'}</span></td><td><button onclick="deletePlan(${p.id})">🗑️</button></td></tr>`;
    });
}

function renderHistory() {
    const tb = document.getElementById('investTableBody'); if(!tb) return;
    tb.innerHTML = '';
    investments.forEach(i => {
        const isRealized = i.realized === true || i.realized === 'yes';
        tb.innerHTML += `<tr><td>${i.name}</td><td>${i.date}</td><td>${i.expiry||'-'}</td><td>${formatCurrency(i.value)}</td><td><span class="${isRealized ? 'text-green' : 'text-red'}">${isRealized ? '✓ Sim' : '✗ Não'}</span></td><td><button onclick="deleteInvestment(${i.id})">🗑️</button></td></tr>`;
    });
}

function deletePlan(id) { plans = plans.filter(p=>p.id!==id); renderPlansTable(); saveLocal(); }

